name: VALIDATE PUSH

on:
  push:
    branches:
      - "**"
      - "!master"
  workflow_call:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: 🚦 Test
        run: echo "Running tests" && true
