name: VALIDATE PR

on:
  pull_request:

jobs:
  validate:
    name: Validate
    if: github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    steps:
      - name: 🚦 Test
        run: echo "Running tests" && true

